let moveMotorZIP = Kitronik_Move_Motor.createMoveMotorZIPLED(4)
let headlight1 = moveMotorZIP.range(0, 1)
let headlight2 = moveMotorZIP.range(1, 2)
let rearlight1 = moveMotorZIP.range(2, 3)
let rearlight2 = moveMotorZIP.range(3, 4)
basic.forever(function () {
    basic.showIcon(IconNames.Happy)
    Kitronik_Move_Motor.motorOn(Kitronik_Move_Motor.Motors.MotorLeft, Kitronik_Move_Motor.MotorDirection.Forward, 10)
    headlight1.showColor(Kitronik_Move_Motor.colors(Kitronik_Move_Motor.ZipLedColors.Blue))
    headlight2.showColor(Kitronik_Move_Motor.colors(Kitronik_Move_Motor.ZipLedColors.Purple))
    rearlight1.showColor(Kitronik_Move_Motor.colors(Kitronik_Move_Motor.ZipLedColors.Blue))
    rearlight2.showColor(Kitronik_Move_Motor.colors(Kitronik_Move_Motor.ZipLedColors.Purple))
})
